Importing the libraries.

In [13]:
import numpy as np
import pandas as pd

Reading the dataset.

In [14]:
df = pd.read_csv('Datasets/cars.csv')
print(df.sample(5))

           brand  km_driven    fuel                 owner  selling_price
5914  Volkswagen      90000  Diesel           Third Owner         280000
616       Maruti      40000  Petrol           First Owner         220000
1555      Maruti     100000  Petrol  Fourth & Above Owner          90000
1703       Honda      35000  Petrol           First Owner         500000
3041    Mahindra     120000  Diesel           First Owner         550000

Finding the all different values in a column.

In [15]:
print(df['brand'].nunique())
print(df['brand'].value_counts())

32
brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [16]:
print(df['fuel'].unique())
print(df['fuel'].value_counts())

['Diesel' 'Petrol' 'LPG' 'CNG']
fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [17]:
print(df['owner'].unique())
print(df['owner'].value_counts())

['First Owner' 'Second Owner' 'Third Owner' 'Fourth & Above Owner'
 'Test Drive Car']
owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

.get_dummies() - It converts categorical values into separate indicator (0/1) columns for One - Hot encoding

In [18]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [19]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

Spliting the data into training and testing part.

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=42)

x_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

Importing OneHotencoder class fomr sklearn.preprocessing ad fit_transforming train data (test data should be avoided).

In [21]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

x_train_new = ohe.fit_transform(x_train[['fuel', 'owner']]).toarray()
x_test_new = ohe.transform(x_test[['fuel', 'owner']]).toarray()

x_train_new[:5]
x_test_new[:5]  
# x_train_new.shape

array([[0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0.]])

Concatenting the array into one single numpy array.

In [22]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(6502, 11), dtype=object)

Removing the brand with value less than a threshold and merging them into a single category as 'Other'

In [23]:
count = df['brand'].value_counts()
print(df['brand'].nunique())
threshold = 100

32

In [24]:
replace_brand = count[count<=threshold].index
pd.get_dummies(df['brand'].replace(replace_brand, 'Other')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Other,Renault,Skoda,Tata,Toyota,Volkswagen
2007,False,False,False,False,False,False,True,False,False,False,False,False,False
7289,False,True,False,False,False,False,False,False,False,False,False,False,False
7890,False,False,False,False,False,False,True,False,False,False,False,False,False
2733,False,False,False,False,False,False,True,False,False,False,False,False,False
5281,False,False,False,False,False,False,True,False,False,False,False,False,False