In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('Datasets/heart_disease_uci.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2, random_state=2)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

lor = LogisticRegression(penalty=None,solver='sag', max_iter=15000)
lor.fit(X_train, y_train)
y_pred1 = lor.predict(X_test)

tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred2 = tree.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9180327868852459
Accuracy of Decision Trees 0.8524590163934426

In [8]:
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred1))
print("Decision Tree Confusion Matrix:\n", confusion_matrix(y_test, y_pred2))

Logistic Regression Confusion Matrix:
 [[27  5]
 [ 0 29]]
Decision Tree Confusion Matrix:
 [[25  7]
 [ 2 27]]

In [9]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.head(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
99              1                               1                         1
296             0                               1                         0
89              1                               1                         1
30              1                               1                         1
234             0                               0                         0
292             0                               0                         0
35              1                               1                         1
7               1                               1                         1
178             0                               0                         0
13              1                               1                         0

In [10]:
from sklearn.metrics import recall_score,precision_score,f1_score
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  27   5
1   0  29
--------------------------------------------------
Precision -  0.8529411764705882
Recall -  1.0
F1 score -  0.9206349206349206

In [11]:
print("For Decision Tree Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model
--------------------------------------------------
    0   1
0  25   7
1   2  27
--------------------------------------------------
Precision -  0.7941176470588235
Recall -  0.9310344827586207
F1 score -  0.8571428571428571

In [13]:
print(precision_score(y_test,y_pred1,average=None))
print(precision_score(y_test,y_pred2,average=None))
print(recall_score(y_test,y_pred1,average=None))
print(recall_score(y_test,y_pred2,average=None))

[1.         0.85294118]
[0.92592593 0.79411765]
[0.84375 1.     ]
[0.78125    0.93103448]