In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('Datasets/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('Species', axis=1), df['Species'], test_size=0.2, random_state=1)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(x_train, y_train)
clf2.fit(x_train, y_train)

y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)
import numpy as np

print(np.array_equal(y_pred1, y_pred2))

False

/home/hardik/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred1))
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred2))

Logistic Regression Accuracy: 1.0
Decision Tree Accuracy: 0.9666666666666667

In [19]:
print("Logistic Regression Confusion Matrix:\n", pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3))))

print("Decision Tree Confusion Matrix\n",pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,3))))

Logistic Regression Confusion Matrix:
     0   1  2
0  11   0  0
1   0  13  0
2   0   0  6
Decision Tree Confusion Matrix
     0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [20]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
141             2                               2                         2
94              1                               1                         1
120             2                               2                         2
35              0                               0                         0
44              0                               0                         0
84              1                               1                         1
14              0                               0                         0
56              1                               1                         1
99              1                               1                         2
29              0                               0                         0

In [21]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1., 1., 1.])

In [22]:
recall_score(y_test,y_pred1,average=None)

array([1., 1., 1.])

In [23]:
df2 = pd.read_csv('Datasets/fashion-mnist.csv')
df2.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df2.iloc[:,1:],df2.iloc[:,0],test_size=0.2,random_state=2)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf1 = LogisticRegression()
clf1.fit(X_train,y_train)
y_pred1 = clf1.predict(X_test)

clf2 = DecisionTreeClassifier()
clf2.fit(X_train,y_train)
y_pred2 = clf2.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

/home/hardik/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy of Logistic Regression 0.8547857142857143
Accuracy of Decision Trees 0.7969285714285714

In [30]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

      0     1     2     3     4     5    6     7     8     9
0  1213    12    28    57     7     0  133     0    19     1
1     3  1343     4    29     3     0    5     0     1     0
2    19     3  1074    12   172     1  122     1    11     0
3    50    24    13  1228    50     0   33     0     5     0
4     3     1   115    51  1130     0   98     0     7     0
5     1     0     0     1     0  1265    1    70    17    46
6   184     6   138    38   181     0  809     0    15     0
7     0     0     0     0     0    45    0  1309     5    46
8     9     1    14    13     6     5   23     2  1295     1
9     1     0     0     0     0    17    0    53     1  1301

In [31]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

      0     1    2     3    4     5    6     7     8     9
0  1095     6   40    65   11     2  227     0    22     2
1     6  1319    1    41    8     0   12     0     1     0
2    34     9  960    24  218     1  150     1    18     0
3    55    38   24  1136   76     1   61     0    12     0
4    10     7  201    70  963     0  143     0     9     2
5     4     0    2     3    2  1241    3    90    17    39
6   199    12  165    61  155     3  758     0    15     3
7     2     0    0     0    0    78    0  1228     9    88
8    15     2   18     9   12    25   34     9  1240     5
9     2     0    1     2    0    39    4   100     8  1217

In [33]:
from sklearn.metrics import precision_score,recall_score,f1_score
print("Precision of Logistic Regression\n",precision_score(y_test,y_pred1,average="weighted"))
print("Recall of Logistic Regression\n",recall_score(y_test,y_pred1,average="weighted"))
print("F1 Score of Logistic Regression\n",f1_score(y_test,y_pred1,average="weighted"))

Precision of Logistic Regression
 0.8540524349993494
Recall of Logistic Regression
 0.8547857142857143
F1 Score of Logistic Regression
 0.8539481953402825

In [34]:

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1470
           1       0.97      0.97      0.97      1388
           2       0.77      0.76      0.77      1415
           3       0.86      0.88      0.87      1403
           4       0.73      0.80      0.77      1405
           5       0.95      0.90      0.93      1401
           6       0.66      0.59      0.62      1371
           7       0.91      0.93      0.92      1405
           8       0.94      0.95      0.94      1369
           9       0.93      0.95      0.94      1373

    accuracy                           0.85     14000
   macro avg       0.85      0.85      0.85     14000
weighted avg       0.85      0.85      0.85     14000